### ISSUE TITLE
大佬可以用了吗

### ISSUE THREAD

**Issue by vinzst** [feilongproject/KazuhaBot#1]
有没有教程啊

**Comment by feilongproject** [comment]
> 有没有教程啊

```面包会有的，牛奶会有的，一切都会有的```
目前写了个简易版使用指南，等有空了在wiki里面写个具体的

**Comment by feilongproject** [comment]
[Wiki](https://github.com/feilongproject/KazuhaBot/wiki)基本编写完毕，基本可以使用
