### ISSUE TITLE
机器人没有反应是为什么

### ISSUE THREAD

**Issue by bangbanbab** [feilongproject/KazuhaBot#10]
![image](https://user-images.githubusercontent.com/87685982/208908061-23caf1bb-5d80-457d-acbb-287855c232c8.png)

**Comment by bangbanbab** [comment]
对私聊好像也没有反应

**Comment by feilongproject** [comment]
`ck绑定`只能在私聊场景使用
其

**Comment by feilongproject** [comment]
ck绑定只能在私聊场景使用（暂不支持仅uid绑定）
频道内指令目前未对@情况做处理，预计目前正在重构的2.0版本可能会加入支持（不过这几天阳了，更新会暂停几天）
