### ISSUE TITLE
绑定cookie无反应

### ISSUE THREAD

**Issue by kongxiangyiren** [feilongproject/KazuhaBot#4]
看样子米游社改了cookie

**Comment by feilongproject** [comment]
![9TLIODP$9`$K@X8{N%7V{6S](https://user-images.githubusercontent.com/43880786/204513283-2adae8ee-5544-47f2-9678-38eb5512db26.jpg)

**Comment by kongxiangyiren** [comment]
米游社改了cookie，然后你的cookie判断还是原来的，所以导致绑定cookie无反应
![image](https://user-images.githubusercontent.com/72970235/204679974-feb7fb59-003c-419d-af8c-278b74b99d66.png)
![image](https://user-images.githubusercontent.com/72970235/204680069-855645fb-c5f9-4212-90ea-3c9a4c9379c7.png)
![image](https://user-images.githubusercontent.com/72970235/204680165-2e30c410-9eee-450f-bf30-c27792d7cf36.png)
![image](https://user-images.githubusercontent.com/72970235/204680267-ee1dbb85-bcad-4d88-98a5-86b4d0422b2c.png)
